name: Build Artifacts

on:
  push:
    branches:
      - '*'
      - '!release'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build partial-kt
        run: |
          chmod +x gradlew
          ./gradlew :example:build publishToMavenLocal --no-daemon --stacktrace
